version: "3.8"
services:
  mongo:
    container_name: jsreport-mongo-container
    image: mongo
    restart: always
    ports:
      - "27050:27017"
    volumes:
      - jsreport-mongo-data:/data/db
    networks:
      - jsreport
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2GB
  jsreport:
    container_name: jsreport
    image: kyawthihadev/jsreport
    depends_on:
      - mongo
    environment:
      - TZ=Asia/Yangon
    ports:
      - "2294:5488"
    restart: always
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G
    networks:
      - jsreport

volumes:
  jsreport-mongo-data:


networks:
  jsreport:
